### ISSUE TITLE
Обработка статуса ответа сервера (404, 400, 302, 422) в action/lists.

### ISSUE THREAD

**Issue by roman82direct** [Cray-code/ToDo-BZ#34]
Работает Роман.

У кого есть живой код настройки api-middleware Реакт-redux на отработку статусов сервера, отзовитесь. В сети на эту тему материала очень мало.

**Comment by AndreSmrnv** [comment]
самый простой вариант:

**Comment by AndreSmrnv** [comment]
import { RSAA, getJSON } from 'redux-api-middleware';
type: 'SEND_SUCCESS',
        payload: async (action, state, responce) => {
          try {
            const res = await getJSON(responce);
            if (res.ok) {
              return { data: reqBody }; 
            }
          }
          catch(err) {
            console.log(err);
            return { data: { name: 'System', text: 'Send failed' } };
          }
        },
